---
- name: Create world data directory
  file:
    path: "{{ mbsmanager_datadir }}/worlds"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Restore initial state (optional)
  unarchive:
    creates: "{{ mbsmanager_datadir }}/worlds/{{ mbsmanager_initial_state_name }}/"
    src: "{{ mbsmanager_initial_state_archive }}"
    dest: "{{ mbsmanager_datadir }}/worlds/"
  when:
    - mbsmanager_initial_state_archive is defined
    - mbsmanager_initial_state_name is defined

- name: Copy initial permissions
  copy:
    src: "{{ mbsmanager_permissions_file }}"
    dest: "{{ mbsmanager_datadir }}/permissions.json"
    force: false

- name: Copy initial whitelist
  copy:
    src: "{{ mbsmanager_whitelist_file }}"
    dest: "{{ mbsmanager_datadir }}/whitelist.json"
    force: false

- name: Copy server configuration
  copy:
    src: "{{ mbsmanager_properties_file }}"
    dest: "{{ mbsmanager_datadir }}/server.properties"

- name: Create systemd unit file
  template:
    src: minecraft-bedrock-server.service.j2
    dest: /etc/systemd/system/minecraft-bedrock-server.service
  notify:
    - Restart Minecraft Bedrock Server

- name: Start mbs-manager for Minecraft Bedrock Server
  systemd:
    name: minecraft-bedrock-server
    daemon_reload: true
    state: started
    enabled: yes
